---
# tasks file for locale
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements
  package:
    name: "{{ locale_requirements }}"
    state: present
  register: locale_install_requirements
  until: locale_install_requirements is succeeded
  retries: 3

- name: configure locale.conf
  template:
    src: locale.conf.j2
    dest: "{{ locale_configuration_file }}"
  notify:
    - localectl set-locale
